#!/usr/bin/env python3
"""B1-friendly glossary for the SAT student-tools toolbar (scripts/student_tools.py).

Each entry: word -> (part of speech, short simple-English definition).
Curated for words that appear in SAT Reading/Writing stimuli and Math word
problems but sit above CEFR B1 level.
"""

# word: (pos, definition)
VOCAB = {
    "abate": ("verb", "become less strong"),
    "abolish": ("verb", "end a law or system officially"),
    "absolve": ("verb", "free someone from blame"),
    "abstain": ("verb", "choose not to do something"),
    "abstract": ("adjective", "about ideas, not real objects"),
    "acute": ("adjective", "very serious; sharp"),
    "adhere": ("verb", "stick to rules"),
    "adjacent": ("adjective", "right next to"),
    "adorn": ("verb", "decorate"),
    "adverse": ("adjective", "harmful; opposing you"),
    "advocate": ("verb", "support an idea publicly"),
    "aesthetic": ("adjective", "about beauty"),
    "affluent": ("adjective", "rich"),
    "agile": ("adjective", "moving fast and easily"),
    "agitate": ("verb", "make people worried; stir up"),
    "alleviate": ("verb", "make pain or problems smaller"),
    "allocate": ("verb", "give parts out for a purpose"),
    "ambiguous": ("adjective", "having two possible meanings"),
    "ambivalent": ("adjective", "having mixed feelings"),
    "amplify": ("verb", "make louder or stronger"),
    "analogous": ("adjective", "similar in a useful way"),
    "anecdote": ("noun", "short interesting story"),
    "animosity": ("noun", "strong hatred"),
    "annotate": ("verb", "add short notes to a text"),
    "anomaly": ("noun", "something different from normal"),
    "antagonist": ("noun", "enemy; opponent"),
    "antiquated": ("adjective", "very old; no longer useful"),
    "antithesis": ("noun", "exact opposite"),
    "apathetic": ("adjective", "showing no interest"),
    "apex": ("noun", "highest point"),
    "appease": ("verb", "calm someone by giving in"),
    "append": ("verb", "add at the end"),
    "appraise": ("verb", "judge the value of"),
    "apprehensive": ("adjective", "afraid something bad will happen"),
    "apt": ("adjective", "suitable; quick to learn"),
    "arbitrary": ("adjective", "random; without reason"),
    "archaic": ("adjective", "very old-fashioned"),
    "archetype": ("noun", "typical example of a kind"),
    "ardent": ("adjective", "passionate"),
    "arduous": ("adjective", "needing great effort"),
    "arid": ("adjective", "very dry"),
    "arrogant": ("adjective", "thinking you are better than others"),
    "articulate": ("adjective", "expressing ideas clearly"),
    "artifact": ("noun", "historic man-made object"),
    "artisan": ("noun", "skilled maker of things by hand"),
    "ascend": ("verb", "go up; climb"),
    "ascertain": ("verb", "find out for sure"),
    "ascribe": ("verb", "say something caused it"),
    "aspiration": ("noun", "strong hope or ambition"),
    "assail": ("verb", "attack strongly"),
    "assent": ("verb", "agree"),
    "assert": ("verb", "state firmly"),
    "assess": ("verb", "judge amount or value"),
    "assiduous": ("adjective", "hardworking and careful"),
    "assimilate": ("verb", "absorb and understand fully"),
    "assuage": ("verb", "make bad feelings weaker"),
    "assurance": ("noun", "promise; confidence"),
    "astute": ("adjective", "clever at reading situations"),
    "attest": ("verb", "prove to be true"),
    "audacious": ("adjective", "bold; rudely daring"),
    "augment": ("verb", "make bigger"),
    "austere": ("adjective", "very plain; strict"),
    "authoritarian": ("adjective", "demanding total obedience"),
    "autonomy": ("noun", "freedom to rule yourself"),
    "aversion": ("noun", "strong dislike"),
    "avert": ("verb", "prevent; turn away"),
    "avid": ("adjective", "very eager"),
    "banal": ("adjective", "boring from being too common"),
    "belie": ("verb", "give a false idea of"),
    "belittle": ("verb", "make seem small"),
    "bellicose": ("adjective", "wanting to fight"),
    "bemused": ("adjective", "confused"),
    "benevolent": ("adjective", "kind; helpful"),
    "benign": ("adjective", "gentle; harmless"),
    "berate": ("verb", "scold angrily"),
    "beset": ("verb", "troubled on all sides"),
    "bias": ("noun", "unfair preference"),
    "bizarre": ("adjective", "very strange"),
    "blight": ("noun", "thing that ruins growth"),
    "bolster": ("verb", "support; strengthen"),
    "bombastic": ("adjective", "full of empty big words"),
    "boon": ("noun", "helpful blessing"),
    "breach": ("noun", "break in a wall or rule"),
    "broach": ("verb", "bring up a hard topic"),
    "brood": ("verb", "think sadly for a long time"),
    "bucolic": ("adjective", "pleasantly rural"),
    "bulwark": ("noun", "strong defense"),
    "burgeon": ("verb", "grow quickly"),
    "cacophony": ("noun", "loud unpleasant noise"),
    "cajole": ("verb", "persuade with flattery"),
    "calamity": ("noun", "disaster"),
    "candid": ("adjective", "honest; direct"),
    "capricious": ("adjective", "changing suddenly"),
    "captivate": ("verb", "hold attention; charm"),
    "cascade": ("verb", "pour down fast"),
    "castigate": ("verb", "punish or blame harshly"),
    "catalyst": ("noun", "thing that speeds up change"),
    "categorical": ("adjective", "absolute; direct"),
    "caustic": ("adjective", "biting; sarcastic"),
    "cede": ("verb", "give up power"),
    "censor": ("verb", "cut parts out of text"),
    "censure": ("verb", "blame strongly"),
    "census": ("noun", "official count of people"),
    "cerebral": ("adjective", "about thinking"),
    "cessation": ("noun", "a stopping"),
    "chagrin": ("noun", "embarrassment"),
    "charlatan": ("noun", "fraud; faker"),
    "chasm": ("noun", "deep gap"),
    "chastise": ("verb", "punish"),
    "cherish": ("verb", "love and protect dearly"),
    "chide": ("verb", "scold mildly"),
    "chronic": ("adjective", "lasting a long time"),
    "cite": ("verb", "quote as proof"),
    "civil": ("adjective", "polite; about citizens"),
    "clandestine": ("adjective", "secret"),
    "clemency": ("noun", "mercy in punishment"),
    "coalesce": ("verb", "join into one"),
    "coerce": ("verb", "force someone"),
    "cogent": ("adjective", "clear and convincing"),
    "coherent": ("adjective", "clear and logically joined"),
    "cohesive": ("adjective", "sticking well together"),
    "coincide": ("verb", "happen at the same time"),
    "colloquial": ("adjective", "everyday spoken style"),
    "collude": ("verb", "plot secretly to cheat"),
    "colossal": ("adjective", "huge"),
    "commemorate": ("verb", "honor the memory of"),
    "commend": ("verb", "praise"),
    "commonplace": ("adjective", "ordinary"),
    "compassion": ("noun", "deep sympathy"),
    "compel": ("verb", "force"),
    "compensate": ("verb", "make up for"),
    "complacent": ("adjective", "too satisfied to see danger"),
    "complement": ("verb", "complete something nicely"),
    "compliant": ("adjective", "obeying rules"),
    "component": ("noun", "a part"),
    "composed": ("adjective", "calm"),
    "comprise": ("verb", "be made of"),
    "compulsion": ("noun", "strong urge to act"),
    "concede": ("verb", "admit; give in"),
    "conceit": ("noun", "too much pride"),
    "concise": ("adjective", "short and clear"),
    "concord": ("noun", "harmony; agreement"),
    "concur": ("verb", "agree"),
    "condemn": ("verb", "say is very bad; punish"),
    "condense": ("verb", "make shorter or thicker"),
    "condone": ("verb", "forgive; allow"),
    "conducive": ("adjective", "helping to cause"),
    "conduit": ("noun", "channel that carries"),
    "confer": ("verb", "grant; discuss"),
    "confide": ("verb", "tell a secret to"),
    "confidential": ("adjective", "secret"),
    "confiscate": ("verb", "take away officially"),
    "conflate": ("verb", "mix together wrongly"),
    "conform": ("verb", "follow rules; match"),
    "confound": ("verb", "confuse; prove wrong"),
    "congenial": ("adjective", "friendly; pleasant"),
    "congregate": ("verb", "gather together"),
    "conjecture": ("noun", "a guess"),
    "connoisseur": ("noun", "expert judge of art or food"),
    "connote": ("verb", "suggest an extra meaning"),
    "conquer": ("verb", "defeat; overcome"),
    "conscientious": ("adjective", "careful and dutiful"),
    "consensus": ("noun", "general agreement"),
    "consent": ("noun", "permission"),
    "conserve": ("verb", "protect from loss"),
    "console": ("verb", "comfort"),
    "consolidate": ("verb", "join into a stronger whole"),
    "conspicuous": ("adjective", "easy to see"),
    "conspire": ("verb", "plot secretly"),
    "constituent": ("noun", "a part; a voter"),
    "constitute": ("verb", "make up; form"),
    "constrain": ("verb", "limit forcefully"),
    "construe": ("verb", "explain the meaning of"),
    "contemplate": ("verb", "think deeply about"),
    "contemporary": ("adjective", "modern; of the same time"),
    "contempt": ("noun", "lack of respect"),
    "contend": ("verb", "argue; compete"),
    "contentious": ("adjective", "causing arguments"),
    "context": ("noun", "surrounding meaning"),
    "contingent": ("adjective", "depending on something"),
    "contort": ("verb", "twist out of shape"),
    "contradict": ("verb", "say the opposite of"),
    "contrite": ("adjective", "sorry for wrongdoing"),
    "contrive": ("verb", "cleverly plan"),
    "controversial": ("adjective", "causing public argument"),
    "conundrum": ("noun", "hard puzzle"),
    "converge": ("verb", "come together"),
    "convey": ("verb", "carry; express"),
    "convict": ("verb", "prove guilty"),
    "convivial": ("adjective", "cheerful and social"),
    "convoluted": ("adjective", "twisted; complex"),
    "copious": ("adjective", "plenty; abundant"),
    "cordial": ("adjective", "warm and friendly"),
    "correlate": ("verb", "connect; be related"),
    "correspond": ("verb", "match; write letters"),
    "corroborate": ("verb", "support with proof"),
    "corrode": ("verb", "eat away slowly"),
    "cosmopolitan": ("adjective", "worldly; multi-culture"),
    "countenance": ("noun", "face; approval"),
    "counterfeit": ("adjective", "fake"),
    "counterintuitive": ("adjective", "against what you expect"),
    "counterpart": ("noun", "matching person or thing"),
    "covert": ("adjective", "secret"),
    "covet": ("verb", "want badly"),
    "cower": ("verb", "shrink back in fear"),
    "craft": ("noun", "skill; clever trick"),
    "crass": ("adjective", "crude and rude"),
    "credible": ("adjective", "believable"),
    "credulous": ("adjective", "too ready to believe"),
    "crescendo": ("noun", "growing climax"),
    "crestfallen": ("adjective", "sad and defeated"),
    "cryptic": ("adjective", "mysteriously unclear"),
    "culminate": ("verb", "reach the highest point"),
    "culpable": ("adjective", "guilty"),
    "cultivate": ("verb", "grow; develop"),
    "cumbersome": ("adjective", "heavy and awkward"),
    "cumulative": ("adjective", "growing by additions"),
    "curator": ("noun", "museum keeper"),
    "curb": ("verb", "hold back; limit"),
    "cursory": ("adjective", "quick; not thorough"),
    "curt": ("adjective", "rudely brief"),
    "curtail": ("verb", "cut short"),
    "cynical": ("adjective", "believing people are selfish"),
    "daunt": ("verb", "frighten"),
    "dearth": ("noun", "a lack"),
    "debilitate": ("verb", "weaken"),
    "decimate": ("verb", "destroy a large part of"),
    "decorum": ("noun", "proper behavior"),
    "deference": ("noun", "respect"),
    "defame": ("verb", "ruin the reputation of"),
    "defer": ("verb", "delay; yield to"),
    "definitive": ("adjective", "final; certain"),
    "deflect": ("verb", "turn aside"),
    "defunct": ("adjective", "dead; no longer working"),
    "dejected": ("adjective", "sad"),
    "deleterious": ("adjective", "harmful"),
    "deliberate": ("adjective", "intentional"),
    "delineate": ("verb", "outline; describe"),
    "delude": ("verb", "fool"),
    "deluge": ("noun", "flood"),
    "delusion": ("noun", "false belief"),
    "demeanor": ("noun", "behavior; manner"),
    "demise": ("noun", "death; end"),
    "demolish": ("verb", "tear down"),
    "demoralize": ("verb", "destroy the spirit of"),
    "demure": ("adjective", "shy and modest"),
    "denigrate": ("verb", "blacken the reputation of"),
    "denote": ("verb", "mean; mark"),
    "denounce": ("verb", "condemn publicly"),
    "deplete": ("verb", "use up"),
    "deplore": ("verb", "strongly disapprove of"),
    "deploy": ("verb", "move into action"),
    "depreciate": ("verb", "lose value"),
    "deride": ("verb", "mock"),
    "derive": ("verb", "get from a source"),
    "derogatory": ("adjective", "insulting"),
    "descend": ("verb", "go down"),
    "designate": ("verb", "mark; appoint"),
    "desolate": ("adjective", "empty and sad"),
    "despair": ("noun", "loss of hope"),
    "despise": ("verb", "hate deeply"),
    "despondent": ("adjective", "hopeless"),
    "destitute": ("adjective", "extremely poor"),
    "deter": ("verb", "discourage"),
    "deteriorate": ("verb", "get worse"),
    "detest": ("verb", "hate"),
    "detract": ("verb", "take value away"),
    "detrimental": ("adjective", "harmful"),
    "devastate": ("verb", "destroy"),
    "deviate": ("verb", "stray from the path"),
    "devious": ("adjective", "sneaky"),
    "devise": ("verb", "invent; plan"),
    "devoid": ("adjective", "empty of"),
    "devout": ("adjective", "deeply religious"),
    "dexterous": ("adjective", "skillful with hands"),
    "dichotomy": ("noun", "two opposite parts"),
    "didactic": ("adjective", "meant to teach a moral"),
    "diffident": ("adjective", "shy; unsure"),
    "diffuse": ("verb", "spread out"),
    "digress": ("verb", "wander off topic"),
    "dilapidated": ("adjective", "ruined; shabby"),
    "dilemma": ("noun", "hard choice"),
    "diligent": ("adjective", "hardworking"),
    "dilute": ("verb", "weaken by mixing"),
    "diminish": ("verb", "make smaller"),
    "dire": ("adjective", "terrible; urgent"),
    "disarray": ("noun", "disorder"),
    "discerning": ("adjective", "showing good judgment"),
    "disclose": ("verb", "reveal"),
    "discord": ("noun", "disagreement"),
    "discreet": ("adjective", "careful and private"),
    "discrepancy": ("noun", "difference; mismatch"),
    "discrete": ("adjective", "separate"),
    "discriminate": ("verb", "tell apart; treat unfairly"),
    "disdain": ("noun", "contempt"),
    "disgruntled": ("adjective", "annoyed; unhappy"),
    "dishearten": ("verb", "discourage"),
    "disjointed": ("adjective", "disconnected"),
    "disparage": ("verb", "belittle"),
    "disparate": ("adjective", "very different"),
    "dispatch": ("verb", "send off quickly"),
    "dispel": ("verb", "drive away"),
    "disperse": ("verb", "scatter"),
    "displace": ("verb", "move from its place"),
    "dispose": ("verb", "get rid of"),
    "disposition": ("noun", "nature; character"),
    "disquiet": ("noun", "worry"),
    "disregard": ("verb", "ignore"),
    "disrupt": ("verb", "break apart; disturb"),
    "dissect": ("verb", "cut apart; analyze"),
    "disseminate": ("verb", "spread widely"),
    "dissent": ("verb", "disagree"),
    "dissipate": ("verb", "scatter; waste"),
    "dissolve": ("verb", "melt away; end"),
    "dissonance": ("noun", "clash; lack of harmony"),
    "dissuade": ("verb", "advise against"),
    "distill": ("verb", "purify; shorten"),
    "distinct": ("adjective", "clearly different"),
    "distort": ("verb", "twist the truth of"),
    "distraught": ("adjective", "deeply upset"),
    "divergent": ("adjective", "differing"),
    "diverse": ("adjective", "varied"),
    "divert": ("verb", "turn aside"),
    "divine": ("adjective", "godly; lovely"),
    "divulge": ("verb", "reveal a secret"),
    "docile": ("adjective", "obedient; tame"),
    "doctrine": ("noun", "system of beliefs"),
    "dogged": ("adjective", "stubbornly persistent"),
    "dogmatic": ("adjective", "rigid in beliefs"),
    "dour": ("adjective", "gloomy; stern"),
    "droll": ("adjective", "funny in an odd way"),
    "drudgery": ("noun", "boring hard work"),
    "dubious": ("adjective", "doubtful"),
    "dupe": ("verb", "fool; trick"),
    "duplicity": ("noun", "double-dealing"),
    "durable": ("adjective", "long-lasting"),
    "dynamic": ("adjective", "energetic; changing"),
    "earnest": ("adjective", "serious; sincere"),
    "eccentric": ("adjective", "odd; unusual"),
    "eclectic": ("adjective", "picked from many sources"),
    "efficacy": ("noun", "power to work well"),
    "effusive": ("adjective", "overflowing with feeling"),
    "egotistical": ("adjective", "self-centered"),
    "elaborate": ("adjective", "detailed; complex"),
    "elated": ("adjective", "very happy"),
    "elicit": ("verb", "draw out an answer"),
    "elite": ("noun", "top group"),
    "eloquent": ("adjective", "speaking beautifully"),
    "elucidate": ("verb", "make clear"),
    "elude": ("verb", "escape from"),
    "emanate": ("verb", "flow out from"),
    "emancipate": ("verb", "set free"),
    "embark": ("verb", "start a journey or task"),
    "embed": ("verb", "fix firmly inside"),
    "embellish": ("verb", "decorate; add details to"),
    "embody": ("verb", "give form to; represent"),
    "eminent": ("adjective", "famous; respected"),
    "emit": ("verb", "give out"),
    "empathy": ("noun", "feeling others' pain"),
    "empirical": ("adjective", "based on observation"),
    "emulate": ("verb", "copy to equal"),
    "enact": ("verb", "make into law; act out"),
    "encapsulate": ("verb", "sum up in short form"),
    "encompass": ("verb", "include; surround"),
    "encroach": ("verb", "intrude slowly"),
    "endemic": ("adjective", "native to a place"),
    "endorse": ("verb", "approve publicly"),
    "endow": ("verb", "give funds or gifts to"),
    "endure": ("verb", "last; suffer through"),
    "enervate": ("verb", "drain of energy"),
    "engender": ("verb", "produce; cause"),
    "enigma": ("noun", "mystery"),
    "enlighten": ("verb", "give knowledge to"),
    "enmity": ("noun", "hatred"),
    "ensue": ("verb", "follow as a result"),
    "entail": ("verb", "involve as necessary"),
    "entice": ("verb", "tempt"),
    "entity": ("noun", "a separate being"),
    "entreat": ("verb", "beg"),
    "entrench": ("verb", "fix firmly"),
    "entrepreneur": ("noun", "person starting a business"),
    "enumerate": ("verb", "list one by one"),
    "envelop": ("verb", "wrap around"),
    "envisage": ("verb", "imagine as future"),
    "ephemeral": ("adjective", "short-lived"),
    "epidemic": ("noun", "fast-spreading disease"),
    "epitome": ("noun", "perfect example"),
    "epoch": ("noun", "a long era"),
    "equanimity": ("noun", "calmness under stress"),
    "equitable": ("adjective", "fair"),
    "equity": ("noun", "fairness"),
    "equivocal": ("adjective", "unclear; two meanings"),
    "eradicate": ("verb", "wipe out"),
    "erode": ("verb", "wear away slowly"),
    "err": ("verb", "make a mistake"),
    "erratic": ("adjective", "unsteady; random"),
    "erroneous": ("adjective", "wrong"),
    "erudite": ("adjective", "deeply learned"),
    "escalate": ("verb", "grow more intense"),
    "eschew": ("verb", "avoid"),
    "esoteric": ("adjective", "understood by few"),
    "espouse": ("verb", "support a cause"),
    "esteem": ("noun", "respect"),
    "estranged": ("adjective", "cut off from old friends"),
    "ethical": ("adjective", "moral"),
    "ethnic": ("noun", "of a culture group"),
    "ethos": ("noun", "spirit of a group"),
    "euphemism": ("noun", "soft word for harsh thing"),
    "evacuate": ("verb", "leave for safety"),
    "evade": ("verb", "escape; avoid"),
    "evaluate": ("verb", "judge the value of"),
    "eventual": ("adjective", "final; in the end"),
    "evict": ("verb", "force to leave"),
    "evoke": ("verb", "call up feelings"),
    "exacerbate": ("verb", "make worse"),
    "exact": ("verb", "demand and take"),
    "exalt": ("verb", "praise highly"),
    "exasperate": ("verb", "annoy greatly"),
    "excerpt": ("noun", "short quoted part"),
    "exemplary": ("adjective", "a perfect model"),
    "exempt": ("adjective", "freed from a rule"),
    "exonerate": ("verb", "clear from blame"),
    "exorbitant": ("adjective", "far too high"),
    "exotic": ("adjective", "strangely foreign"),
    "expanse": ("noun", "wide open area"),
    "expedient": ("adjective", "handy but not moral"),
    "expedite": ("verb", "speed up"),
    "expedition": ("noun", "organized journey"),
    "expel": ("verb", "drive out"),
    "expend": ("verb", "spend; use up"),
    "expire": ("verb", "run out; die"),
    "explicit": ("adjective", "stated clearly"),
    "exploit": ("verb", "use unfairly"),
    "exquisite": ("adjective", "extremely beautiful"),
    "exterminate": ("verb", "wipe out fully"),
    "extinct": ("adjective", "no longer existing"),
    "extinguish": ("verb", "put out"),
    "extol": ("verb", "praise highly"),
    "extort": ("verb", "get by threats"),
    "extract": ("verb", "pull out"),
    "extraneous": ("adjective", "not belonging"),
    "extrapolate": ("verb", "guess beyond known data"),
    "extravagant": ("adjective", "spending too much"),
    "extricate": ("verb", "free from difficulty"),
    "exuberant": ("adjective", "full of energy"),
    "fabricate": ("verb", "invent falsely; build"),
    "facade": ("noun", "false front"),
    "facet": ("noun", "one side of many"),
    "facetious": ("adjective", "joking at wrong time"),
    "facile": ("adjective", "too easy; shallow"),
    "facilitate": ("verb", "make easier"),
    "faction": ("noun", "splinter group"),
    "faculty": ("noun", "teachers; ability"),
    "fallacious": ("adjective", "based on error"),
    "falter": ("verb", "hesitate; stumble"),
    "fanatic": ("noun", "extreme believer"),
    "farce": ("noun", "ridiculous show"),
    "fastidious": ("adjective", "hard to please"),
    "fatal": ("adjective", "deadly"),
    "fathom": ("verb", "understand deeply"),
    "fauna": ("noun", "animals of a region"),
    "feasible": ("adjective", "possible to do"),
    "feeble": ("adjective", "weak"),
    "feign": ("verb", "pretend"),
    "fell": ("verb", "cut down"),
    "ferment": ("verb", "brew; excite"),
    "ferocious": ("adjective", "fierce"),
    "fertile": ("adjective", "producing much"),
    "fervent": ("adjective", "passionate"),
    "fervor": ("noun", "passion"),
    "fester": ("verb", "rot; grow bitter"),
    "fetter": ("verb", "chain; restrain"),
    "feud": ("noun", "long bitter fight"),
    "fiasco": ("noun", "total failure"),
    "fickle": ("adjective", "changing loyally fast"),
    "fictitious": ("adjective", "made up"),
    "fidelity": ("noun", "loyalty"),
    "finite": ("adjective", "having limits"),
    "finesse": ("noun", "delicate skill"),
    "fissure": ("noun", "narrow crack"),
    "flagrant": ("adjective", "shamelessly bad"),
    "flamboyant": ("adjective", "flashy"),
    "flaunt": ("verb", "show off"),
    "flaw": ("noun", "a fault"),
    "fleeting": ("adjective", "passing fast"),
    "flinch": ("verb", "shrink from fear"),
    "flippant": ("adjective", "not serious enough"),
    "flora": ("noun", "plants of a region"),
    "florid": ("adjective", "flowery; reddish"),
    "flounder": ("verb", "struggle clumsily"),
    "flourish": ("verb", "thrive"),
    "flout": ("verb", "mock; disobey"),
    "fluctuate": ("verb", "rise and fall"),
    "foible": ("noun", "small weakness"),
    "foil": ("verb", "prevent from succeeding"),
    "foliage": ("noun", "leaves"),
    "foment": ("verb", "stir up trouble"),
    "foolhardy": ("adjective", "recklessly brave"),
    "forbearance": ("noun", "patience"),
    "foreboding": ("noun", "sense of coming evil"),
    "forensic": ("adjective", "about crime-solving"),
    "forerunner": ("noun", "early sign"),
    "foreshadow": ("verb", "hint at future"),
    "forestall": ("verb", "prevent by acting first"),
    "forfeit": ("verb", "lose as penalty"),
    "forge": ("verb", "make; move ahead"),
    "forgo": ("verb", "give up"),
    "forlorn": ("adjective", "sad and lonely"),
    "formidable": ("adjective", "fearsome; impressive"),
    "forte": ("noun", "strong point"),
    "forthright": ("adjective", "direct; honest"),
    "fortify": ("verb", "strengthen"),
    "fortitude": ("noun", "courage in hardship"),
    "fortuitous": ("adjective", "lucky by chance"),
    "forum": ("noun", "meeting place"),
    "fossil": ("noun", "ancient remains"),
    "foster": ("verb", "encourage growth of"),
    "founder": ("verb", "sink; fail"),
    "fracture": ("noun", "a break; crack"),
    "fragile": ("adjective", "easily broken"),
    "fragment": ("noun", "broken piece"),
    "fragrant": ("adjective", "sweet-smelling"),
    "frail": ("adjective", "weak"),
    "frantic": ("adjective", "wildly hurried"),
    "fraud": ("noun", "cheating for gain"),
    "fraught": ("adjective", "full of"),
    "frenzy": ("noun", "wild excitement"),
    "fret": ("verb", "worry"),
    "friction": ("noun", "rubbing; conflict"),
    "frigid": ("adjective", "very cold"),
    "frivolous": ("adjective", "silly; not serious"),
    "frugal": ("adjective", "careful with money"),
    "fruition": ("noun", "coming true of a plan"),
    "fugitive": ("noun", "runaway"),
    "fundamental": ("adjective", "basic"),
    "furtive": ("adjective", "secretive"),
    "fuse": ("verb", "join by melting"),
    "futile": ("adjective", "useless"),
    "gaffe": ("noun", "social blunder"),
    "gallant": ("adjective", "brave and polite"),
    "gamut": ("noun", "full range"),
    "garble": ("verb", "mix up a message"),
    "gargantuan": ("adjective", "giant"),
    "garish": ("adjective", "too bright; gaudy"),
    "garner": ("verb", "gather; collect"),
    "garrulous": ("adjective", "very talkative"),
    "gauge": ("verb", "measure; judge"),
    "generic": ("adjective", "general; not brand"),
    "genial": ("adjective", "warm and friendly"),
    "genuine": ("adjective", "real"),
    "germane": ("adjective", "relevant"),
    "gist": ("noun", "main point"),
    "glacial": ("adjective", "icy; very slow"),
    "glean": ("verb", "gather bit by bit"),
    "glib": ("adjective", "smooth but shallow"),
    "glimmer": ("noun", "faint gleam"),
    "gloat": ("verb", "brag over victory"),
    "gloom": ("noun", "darkness; sadness"),
    "gloss": ("verb", "explain away"),
    "glut": ("noun", "too much supply"),
    "goad": ("verb", "push into action"),
    "gradient": ("noun", "slope; rate of change"),
    "grandeur": ("noun", "greatness"),
    "grandiose": ("adjective", "overly grand"),
    "grapple": ("verb", "wrestle with"),
    "grate": ("verb", "annoy; shred"),
    "gratify": ("verb", "please"),
    "gratuitous": ("adjective", "free; uncalled for"),
    "grave": ("adjective", "serious"),
    "gregarious": ("adjective", "sociable"),
    "grievance": ("noun", "complaint"),
    "grim": ("adjective", "stern; harsh"),
    "grimace": ("noun", "twisted face"),
    "grotesque": ("adjective", "bizarrely ugly"),
    "grovel": ("verb", "beg humbly"),
    "grudge": ("noun", "long-held anger"),
    "grueling": ("adjective", "exhausting"),
    "gruesome": ("adjective", "horrible"),
    "gruff": ("adjective", "rough-voiced; blunt"),
    "guile": ("noun", "slyness"),
    "guise": ("noun", "outward appearance"),
    "gullible": ("adjective", "easily fooled"),
    "hackneyed": ("adjective", "overused"),
    "hamper": ("verb", "hold back"),
    "haphazard": ("adjective", "random; messy"),
    "harangue": ("noun", "long scolding speech"),
    "harass": ("verb", "bother repeatedly"),
    "harbinger": ("noun", "early sign"),
    "harbor": ("verb", "shelter; hide"),
    "harrowing": ("adjective", "deeply scary"),
    "hasten": ("verb", "hurry"),
    "haughty": ("adjective", "proudly superior"),
    "haven": ("noun", "safe place"),
    "havoc": ("noun", "great destruction"),
    "hazard": ("noun", "danger"),
    "heed": ("verb", "pay attention to"),
    "heinous": ("adjective", "shockingly evil"),
    "herald": ("verb", "announce the start of"),
    "herculean": ("adjective", "needing huge effort"),
    "heresy": ("noun", "belief against the church"),
    "hiatus": ("noun", "a pause"),
    "hierarchy": ("noun", "ranked system"),
    "hinge": ("verb", "depend on"),
    "hoard": ("verb", "store secretly"),
    "homage": ("noun", "respect shown publicly"),
    "hostility": ("noun", "enmity"),
    "hubris": ("noun", "excessive pride"),
    "hue": ("noun", "color; shade"),
    "humane": ("adjective", "kind; merciful"),
    "humdrum": ("adjective", "dull routine"),
    "humiliate": ("verb", "shame"),
    "husband": ("verb", "save carefully"),
    "hybrid": ("noun", "a mix of two kinds"),
    "hyperbole": ("noun", "wild exaggeration"),
    "hypocrisy": ("noun", "saying one thing, doing another"),
    "hypothesis": ("noun", "testable guess"),
    "iconoclast": ("noun", "attacker of traditions"),
    "idiosyncrasy": ("noun", "personal quirk"),
    "idle": ("adjective", "not working; lazy"),
    "idyllic": ("adjective", "perfectly peaceful"),
    "ignite": ("verb", "set on fire"),
    "illuminate": ("verb", "light up; explain"),
    "illusion": ("noun", "false idea"),
    "illusory": ("adjective", "unreal"),
    "illustrious": ("adjective", "famous"),
    "imbue": ("verb", "fill with feeling"),
    "immaterial": ("adjective", "not important"),
    "immense": ("adjective", "huge"),
    "immerse": ("verb", "dip into fully"),
    "imminent": ("adjective", "about to happen"),
    "immune": ("adjective", "protected from"),
    "impair": ("verb", "damage; weaken"),
    "impart": ("verb", "give; tell"),
    "impartial": ("adjective", "fair; neutral"),
    "impasse": ("noun", "deadlock"),
    "impassioned": ("adjective", "full of feeling"),
    "impassive": ("adjective", "showing no feeling"),
    "impeccable": ("adjective", "flawless"),
    "impede": ("verb", "block; slow down"),
    "impel": ("verb", "drive forward"),
    "impending": ("adjective", "coming soon"),
    "impenetrable": ("adjective", "cannot be entered"),
    "imperative": ("adjective", "urgent; commanding"),
    "imperceptible": ("adjective", "too small to notice"),
    "imperil": ("verb", "endanger"),
    "imperious": ("adjective", "bossy"),
    "imperturbable": ("adjective", "always calm"),
    "impervious": ("adjective", "cannot be passed through"),
    "impetuous": ("adjective", "acting fast without thought"),
    "impetus": ("noun", "pushing force"),
    "implacable": ("adjective", "cannot be calmed"),
    "implausible": ("adjective", "hard to believe"),
    "implement": ("verb", "put into action"),
    "implicate": ("verb", "show to be involved"),
    "implicit": ("adjective", "implied; complete"),
    "implore": ("verb", "beg"),
    "impose": ("verb", "force upon"),
    "impoverish": ("verb", "make poor"),
    "impromptu": ("adjective", "unplanned"),
    "improvise": ("verb", "make up on the spot"),
    "imprudent": ("adjective", "unwise"),
    "impudent": ("adjective", "rudely bold"),
    "impugn": ("verb", "challenge as false"),
    "impulse": ("noun", "sudden urge"),
    "impunity": ("noun", "freedom from punishment"),
    "inane": ("adjective", "silly; empty"),
    "inanimate": ("adjective", "not alive"),
    "inaugurate": ("verb", "open formally"),
    "incandescent": ("adjective", "glowing; brilliant"),
    "incarcerate": ("verb", "put in prison"),
    "incendiary": ("adjective", "causing fires or anger"),
    "incense": ("verb", "make very angry"),
    "incentive": ("noun", "reward that motivates"),
    "inception": ("noun", "beginning"),
    "incessant": ("adjective", "never stopping"),
    "incidental": ("adjective", "minor; by chance"),
    "incisive": ("adjective", "sharp and direct"),
    "incite": ("verb", "stir up"),
    "inclement": ("adjective", "stormy; harsh"),
    "incline": ("verb", "lean; tend"),
    "incoherent": ("adjective", "unclear; rambling"),
    "incompatible": ("adjective", "cannot work together"),
    "inconclusive": ("adjective", "not final"),
    "incongruous": ("adjective", "out of place"),
    "inconsequential": ("adjective", "unimportant"),
    "inconspicuous": ("adjective", "not noticeable"),
    "incontrovertible": ("adjective", "cannot be denied"),
    "incorporate": ("verb", "include; join"),
    "incorrigible": ("adjective", "cannot be fixed"),
    "incredulous": ("adjective", "disbelieving"),
    "increment": ("noun", "small increase"),
    "incriminate": ("verb", "show guilt of"),
    "inculcate": ("verb", "teach by repeating"),
    "incumbent": ("adjective", "holding office now"),
    "incur": ("verb", "bring upon yourself"),
    "indefatigable": ("adjective", "never tiring"),
    "indelible": ("adjective", "cannot be erased"),
    "indeterminate": ("adjective", "unclear; vague"),
    "indict": ("verb", "charge with crime"),
    "indifferent": ("adjective", "not caring"),
    "indigenous": ("adjective", "native to a place"),
    "indigent": ("adjective", "poor; needy"),
    "indignant": ("adjective", "angry at unfairness"),
    "indiscriminate": ("adjective", "random; unselective"),
    "indispensable": ("adjective", "absolutely needed"),
    "indisputable": ("adjective", "cannot be argued"),
    "indistinct": ("adjective", "unclear"),
    "indoctrinate": ("verb", "teach one-sided ideas to"),
    "indolent": ("adjective", "lazy"),
    "indomitable": ("adjective", "cannot be beaten"),
    "induce": ("verb", "persuade; cause"),
    "indulge": ("verb", "give in to pleasure"),
    "industrious": ("adjective", "hardworking"),
    "inept": ("adjective", "clumsy; unskilled"),
    "inert": ("adjective", "not moving"),
    "inevitable": ("adjective", "sure to happen"),
    "inexorable": ("adjective", "cannot be stopped"),
    "inexplicable": ("adjective", "cannot be explained"),
    "infallible": ("adjective", "never wrong"),
    "infamous": ("adjective", "famous for bad things"),
    "infer": ("verb", "conclude from proof"),
    "inference": ("noun", "conclusion from proof"),
    "inferior": ("adjective", "lower; worse"),
    "infiltrate": ("verb", "enter secretly"),
    "inflame": ("verb", "set on fire; anger"),
    "inflate": ("verb", "fill with air; raise"),
    "inflict": ("verb", "cause pain to"),
    "influx": ("noun", "a flowing in"),
    "infringe": ("verb", "break a rule or right"),
    "infuriate": ("verb", "make furious"),
    "infuse": ("verb", "fill with"),
    "ingenious": ("adjective", "cleverly inventive"),
    "ingenuity": ("noun", "cleverness"),
    "ingenuous": ("adjective", "innocent; honest"),
    "ingrained": ("adjective", "deeply fixed"),
    "ingratiate": ("verb", "win favor sweetly"),
    "inherent": ("adjective", "built-in; natural"),
    "inhibit": ("verb", "hold back"),
    "inimical": ("adjective", "hostile"),
    "inimitable": ("adjective", "cannot be copied"),
    "iniquity": ("noun", "great unfairness"),
    "initiate": ("verb", "begin; admit"),
    "initiative": ("noun", "first step; drive"),
    "inkling": ("noun", "slight hint"),
    "innate": ("adjective", "born with it"),
    "innocuous": ("adjective", "harmless"),
    "innovate": ("verb", "bring in new ideas"),
    "innovation": ("noun", "new idea or method"),
    "innumerable": ("adjective", "too many to count"),
    "inordinate": ("adjective", "excessive"),
    "inquisitive": ("adjective", "eager to learn"),
    "insatiable": ("adjective", "never satisfied"),
    "inscribe": ("verb", "write on; dedicate"),
    "inscrutable": ("adjective", "mysterious"),
    "insidious": ("adjective", "secretly harmful"),
    "insight": ("noun", "deep understanding"),
    "insignificant": ("adjective", "unimportant"),
    "insinuate": ("verb", "hint nastily"),
    "insipid": ("adjective", "dull; tasteless"),
    "insolent": ("adjective", "rudely bold"),
    "instigate": ("verb", "start trouble"),
    "instill": ("verb", "put in slowly"),
    "instinct": ("noun", "natural feeling"),
    "institute": ("verb", "set up; begin"),
    "insular": ("adjective", "narrow; isolated"),
    "insurmountable": ("adjective", "cannot be overcome"),
    "intact": ("adjective", "whole; untouched"),
    "intangible": ("adjective", "cannot be touched"),
    "integral": ("adjective", "essential part of"),
    "integrate": ("verb", "combine into whole"),
    "integrity": ("noun", "honesty; wholeness"),
    "intellect": ("noun", "power of mind"),
    "intellectual": ("adjective", "about thinking"),
    "intensify": ("verb", "make stronger"),
    "intent": ("adjective", "focused; determined"),
    "interact": ("verb", "act on each other"),
    "intercept": ("verb", "catch on the way"),
    "interfere": ("verb", "get in the way"),
    "interim": ("adjective", "temporary"),
    "interject": ("verb", "interrupt with words"),
    "interlude": ("noun", "pause between acts"),
    "interminable": ("adjective", "endless"),
    "intermittent": ("adjective", "stopping and starting"),
    "intimate": ("adjective", "close and personal"),
    "intimidate": ("verb", "frighten into obeying"),
    "intractable": ("adjective", "hard to control"),
    "intransigent": ("adjective", "refusing to agree"),
    "intrepid": ("adjective", "fearless"),
    "intricate": ("adjective", "finely detailed"),
    "intrigue": ("verb", "fascinate; plot"),
    "intrinsic": ("adjective", "belonging by nature"),
    "intuition": ("noun", "gut feeling"),
    "inundate": ("verb", "flood; overwhelm"),
    "invalidate": ("verb", "make void"),
    "invaluable": ("adjective", "priceless"),
    "inverse": ("adjective", "opposite in order"),
    "invert": ("verb", "turn upside down"),
    "inveterate": ("adjective", "long fixed in habit"),
    "invigorate": ("verb", "give energy to"),
    "invincible": ("adjective", "cannot be beaten"),
    "invoke": ("verb", "call upon"),
    "irascible": ("adjective", "easily angered"),
    "irate": ("adjective", "very angry"),
    "irrefutable": ("adjective", "cannot be disproved"),
    "irreparable": ("adjective", "cannot be fixed"),
    "irresolute": ("adjective", "unable to decide"),
    "irreverent": ("adjective", "disrespectful"),
    "irrevocable": ("adjective", "cannot be undone"),
    "isolate": ("verb", "set apart"),
    "jaded": ("adjective", "tired from too much"),
    "jargon": ("noun", "special words of a group"),
    "jeopardize": ("verb", "endanger"),
    "jeopardy": ("noun", "danger"),
    "jettison": ("verb", "throw overboard"),
    "jovial": ("adjective", "cheerful"),
    "judicious": ("adjective", "wise"),
    "juxtapose": ("verb", "place side by side"),
    "keen": ("adjective", "eager; sharp"),
    "kernel": ("noun", "central seed; core"),
    "kindle": ("verb", "start a fire; excite"),
    "kinetic": ("adjective", "about motion"),
    "labyrinth": ("noun", "maze"),
    "lackadaisical": ("adjective", "lazy; careless"),
    "laconic": ("adjective", "using few words"),
    "lament": ("verb", "mourn"),
    "lampoon": ("verb", "mock publicly"),
    "languid": ("adjective", "slow and weak"),
    "languish": ("verb", "waste away"),
    "lassitude": ("noun", "tiredness"),
    "latent": ("adjective", "hidden; not yet active"),
    "lateral": ("adjective", "sideways"),
    "latitude": ("noun", "freedom to act"),
    "laud": ("verb", "praise"),
    "lavish": ("adjective", "generous; rich"),
    "lax": ("adjective", "loose; careless"),
    "legacy": ("noun", "gift from the past"),
    "legitimate": ("adjective", "lawful; real"),
    "lethargic": ("adjective", "very sleepy; slow"),
    "levity": ("noun", "lack of seriousness"),
    "lexicon": ("noun", "wordbook; vocabulary"),
    "liable": ("adjective", "likely; responsible"),
    "limpid": ("adjective", "clear"),
    "linger": ("verb", "stay longer"),
    "listless": ("adjective", "spiritless"),
    "literal": ("adjective", "exact word-for-word"),
    "livid": ("adjective", "furiously angry"),
    "loath": ("adjective", "unwilling"),
    "loathe": ("verb", "hate"),
    "locale": ("noun", "a place"),
    "lucid": ("adjective", "clear; easy to follow"),
    "lucrative": ("adjective", "profitable"),
    "ludicrous": ("adjective", "ridiculous"),
    "luminous": ("adjective", "glowing"),
    "lull": ("verb", "calm to sleep"),
    "lurid": ("adjective", "shockingly vivid"),
    "lurk": ("verb", "hide waiting"),
    "magnanimous": ("adjective", "generous in forgiving"),
    "magnitude": ("noun", "great size"),
    "mainstream": ("adjective", "normal; popular"),
    "malady": ("noun", "disease"),
    "malaise": ("noun", "vague sickness"),
    "malevolent": ("adjective", "wishing harm"),
    "malice": ("noun", "wish to hurt"),
    "malignant": ("adjective", "deadly; evil"),
    "malleable": ("adjective", "easy to shape"),
    "mammoth": ("adjective", "giant"),
    "mandate": ("noun", "official order"),
    "mandatory": ("adjective", "required"),
    "mania": ("noun", "wild craze"),
    "manifest": ("adjective", "clear; obvious"),
    "manipulate": ("verb", "control cleverly"),
    "mar": ("verb", "spoil"),
    "margin": ("noun", "edge; extra amount"),
    "marginal": ("adjective", "small; edge-related"),
    "marshal": ("verb", "gather in order"),
    "martial": ("adjective", "warlike"),
    "martyr": ("noun", "sufferer for a cause"),
    "masquerade": ("verb", "pretend to be"),
    "maverick": ("noun", "rebel; loner"),
    "maxim": ("noun", "wise saying"),
    "meager": ("adjective", "too small"),
    "meander": ("verb", "wander"),
    "mediate": ("verb", "settle between sides"),
    "mediocre": ("adjective", "average; poor"),
    "meek": ("adjective", "gentle; submissive"),
    "melancholy": ("noun", "deep sadness"),
    "memoir": ("noun", "life story"),
    "mendacious": ("adjective", "lying"),
    "menial": ("adjective", "low boring work"),
    "mentor": ("noun", "wise guide"),
    "mercenary": ("adjective", "working only for money"),
    "mercurial": ("adjective", "quickly changing mood"),
    "merge": ("verb", "join together"),
    "merit": ("noun", "worth; value"),
    "metamorphosis": ("noun", "complete change"),
    "methodical": ("adjective", "orderly"),
    "meticulous": ("adjective", "very careful"),
    "mettle": ("noun", "courage"),
    "microcosm": ("noun", "small model of big thing"),
    "mimic": ("verb", "copy"),
    "minimal": ("adjective", "smallest possible"),
    "minimize": ("verb", "make smallest"),
    "minute": ("adjective", "tiny"),
    "mirage": ("noun", "false vision"),
    "misanthrope": ("noun", "hater of people"),
    "misconception": ("noun", "wrong idea"),
    "misconstrue": ("verb", "understand wrongly"),
    "miserly": ("adjective", "stingy"),
    "misgiving": ("noun", "doubt; worry"),
    "misnomer": ("noun", "wrong name"),
    "misrepresent": ("verb", "describe falsely"),
    "mitigate": ("verb", "make milder"),
    "mock": ("verb", "make fun of"),
    "modicum": ("noun", "small amount"),
    "mollify": ("verb", "calm anger of"),
    "momentous": ("adjective", "very important"),
    "momentum": ("noun", "forward motion"),
    "monolithic": ("adjective", "one solid block"),
    "monotonous": ("adjective", "boringly same"),
    "moot": ("adjective", "open to debate"),
    "morbid": ("adjective", "sickly; gloomy"),
    "mores": ("noun", "customs of a group"),
    "morose": ("adjective", "gloomy"),
    "mortal": ("adjective", "deadly; human"),
    "motif": ("noun", "repeating theme"),
    "muddle": ("verb", "mix up; confuse"),
    "mundane": ("adjective", "ordinary; dull"),
    "murky": ("adjective", "dark and unclear"),
    "muse": ("verb", "think deeply"),
    "muster": ("verb", "gather; summon up"),
    "mutable": ("adjective", "changeable"),
    "mute": ("adjective", "silent"),
    "mutual": ("adjective", "shared both ways"),
    "myriad": ("adjective", "countless"),
    "nadir": ("noun", "lowest point"),
    "naive": ("adjective", "too trusting"),
    "narrative": ("noun", "story"),
    "nascent": ("adjective", "just beginning"),
    "nebulous": ("adjective", "cloudy; vague"),
    "necessitate": ("verb", "make necessary"),
    "nefarious": ("adjective", "wicked"),
    "negate": ("verb", "cancel out"),
    "negligible": ("adjective", "too small to matter"),
    "neophyte": ("noun", "beginner"),
    "nerve": ("noun", "courage"),
    "niche": ("noun", "special place or role"),
    "nimble": ("adjective", "quick and light"),
    "nominal": ("adjective", "in name only; tiny"),
    "nonchalant": ("adjective", "calmly careless"),
    "noncommittal": ("adjective", "not taking sides"),
    "nondescript": ("adjective", "plain; ordinary"),
    "notable": ("adjective", "famous; important"),
    "notorious": ("adjective", "famous for bad things"),
    "nourish": ("verb", "feed; support growth of"),
    "novel": ("adjective", "new and unusual"),
    "novice": ("noun", "beginner"),
    "noxious": ("adjective", "harmful"),
    "nuance": ("noun", "small shade of meaning"),
    "nullify": ("verb", "cancel"),
    "nurture": ("verb", "raise with care"),
    "obdurate": ("adjective", "stubborn"),
    "obfuscate": ("verb", "make unclear"),
    "object": ("verb", "protest"),
    "objective": ("adjective", "fair; not personal"),
    "obligatory": ("adjective", "required"),
    "oblige": ("verb", "do a favor for; force"),
    "oblique": ("adjective", "slanted; indirect"),
    "obliterate": ("verb", "wipe out"),
    "oblivious": ("adjective", "not noticing"),
    "obnoxious": ("adjective", "very unpleasant"),
    "obscene": ("adjective", "shocking; rude"),
    "obscure": ("adjective", "unknown; hard to see"),
    "obsequious": ("adjective", "too eager to obey"),
    "observant": ("adjective", "quick to notice"),
    "obsolete": ("adjective", "no longer used"),
    "obstinate": ("adjective", "stubborn"),
    "obstruct": ("verb", "block"),
    "obtain": ("verb", "get"),
    "obtuse": ("adjective", "slow to understand"),
    "obviate": ("verb", "make unnecessary"),
    "odious": ("adjective", "hateful"),
    "officious": ("adjective", "too eager to help"),
    "ominous": ("adjective", "threatening"),
    "omniscient": ("adjective", "knowing everything"),
    "onerous": ("adjective", "heavy; hard to bear"),
    "opaque": ("adjective", "not clear; dull"),
    "opine": ("verb", "give an opinion"),
    "opportune": ("adjective", "well-timed"),
    "oppress": ("verb", "rule cruelly"),
    "opt": ("verb", "choose"),
    "opulent": ("adjective", "very rich"),
    "orator": ("noun", "public speaker"),
    "ordeal": ("noun", "painful experience"),
    "ornate": ("adjective", "heavily decorated"),
    "orthodox": ("adjective", "traditional"),
    "oscillate": ("verb", "swing back and forth"),
    "ossify": ("verb", "turn rigid"),
    "ostensible": ("adjective", "seeming; stated"),
    "ostentatious": ("adjective", "showing off"),
    "oust": ("verb", "force out"),
    "outmoded": ("adjective", "outdated"),
    "outspoken": ("adjective", "frank"),
    "overt": ("adjective", "open; not hidden"),
    "oxymoron": ("noun", "contradictory phrase"),
    "pacific": ("adjective", "peaceful; calm"),
    "pacify": ("verb", "calm down"),
    "painstaking": ("adjective", "very careful"),
    "palatable": ("adjective", "pleasant to taste or mind"),
    "palpable": ("adjective", "can be felt"),
    "paltry": ("adjective", "too small"),
    "panacea": ("noun", "cure for everything"),
    "pandemic": ("noun", "worldwide disease"),
    "pandemonium": ("noun", "wild chaos"),
    "paradigm": ("noun", "model example"),
    "paradox": ("noun", "seeming contradiction"),
    "paragon": ("noun", "perfect model"),
    "paramount": ("adjective", "most important"),
    "paraphrase": ("verb", "restate in own words"),
    "parched": ("adjective", "dried out"),
    "pare": ("verb", "trim off"),
    "pariah": ("noun", "outcast"),
    "parity": ("noun", "equality"),
    "parochial": ("adjective", "narrow-minded"),
    "parody": ("noun", "funny imitation"),
    "parsimonious": ("adjective", "stingy"),
    "partial": ("adjective", "biased; incomplete"),
    "partisan": ("noun", "strong supporter"),
    "patent": ("adjective", "obvious"),
    "pathos": ("noun", "pity-evoking quality"),
    "paucity": ("noun", "smallness of amount"),
    "pedant": ("noun", "person fussy about rules"),
    "pedestrian": ("adjective", "dull; ordinary"),
    "peer": ("verb", "look closely"),
    "pejorative": ("adjective", "insulting"),
    "pellucid": ("adjective", "clear"),
    "penchant": ("noun", "strong liking"),
    "penitent": ("adjective", "sorry"),
    "pensive": ("adjective", "deeply thoughtful"),
    "penury": ("noun", "extreme poverty"),
    "perceive": ("verb", "notice; understand"),
    "perceptive": ("adjective", "quick to notice"),
    "perennial": ("adjective", "lasting for years"),
    "perfunctory": ("adjective", "done without care"),
    "peril": ("noun", "danger"),
    "perimeter": ("noun", "outer edge"),
    "peripheral": ("adjective", "edge-related; minor"),
    "perish": ("verb", "die; rot"),
    "perjury": ("noun", "lying under oath"),
    "permeate": ("verb", "spread through"),
    "pernicious": ("adjective", "secretly harmful"),
    "perpetrate": ("verb", "commit a crime"),
    "perpetual": ("adjective", "never ending"),
    "perplex": ("verb", "puzzle"),
    "persevere": ("verb", "keep going firmly"),
    "persist": ("verb", "continue firmly"),
    "personify": ("verb", "give human form to"),
    "perspective": ("noun", "point of view"),
    "perspicacious": ("adjective", "wise; sharp-sighted"),
    "pertain": ("verb", "belong to; relate to"),
    "pertinent": ("adjective", "relevant"),
    "perturb": ("verb", "disturb"),
    "peruse": ("verb", "read carefully"),
    "pervasive": ("adjective", "spread everywhere"),
    "pessimism": ("noun", "expecting the worst"),
    "petulant": ("adjective", "childishly grumpy"),
    "phenomenon": ("noun", "remarkable event"),
    "philanthropy": ("noun", "charity to people"),
    "philistine": ("noun", "uncultured person"),
    "phlegmatic": ("adjective", "calm; unemotional"),
    "piety": ("noun", "deep respect for God"),
    "pillory": ("verb", "mock publicly"),
    "pine": ("verb", "long for"),
    "pinnacle": ("noun", "peak"),
    "pious": ("adjective", "deeply religious"),
    "pique": ("verb", "excite interest; offend"),
    "pithy": ("adjective", "short and wise"),
    "pivot": ("verb", "turn on a central point"),
    "placate": ("verb", "calm anger of"),
    "placid": ("adjective", "calm"),
    "plaintive": ("adjective", "sad-sounding"),
    "platitude": ("noun", "dull obvious remark"),
    "plaudit": ("noun", "praise"),
    "plausible": ("adjective", "believable"),
    "plebeian": ("adjective", "common; low-class"),
    "plethora": ("noun", "too much"),
    "pliant": ("adjective", "easily bent"),
    "plight": ("noun", "bad situation"),
    "plummet": ("verb", "fall fast"),
    "plunder": ("verb", "rob"),
    "poignant": ("adjective", "moving; painful"),
    "poised": ("adjective", "calm and ready"),
    "polarize": ("verb", "split into opposites"),
    "polemic": ("noun", "angry argument"),
    "ponder": ("verb", "think deeply"),
    "ponderous": ("adjective", "heavy and dull"),
    "pontificate": ("verb", "speak pompously"),
    "populace": ("noun", "the people"),
    "populous": ("adjective", "full of people"),
    "porous": ("adjective", "full of holes"),
    "portend": ("verb", "warn of future"),
    "portent": ("noun", "warning sign"),
    "posit": ("verb", "assume as fact"),
    "potent": ("adjective", "powerful"),
    "pragmatic": ("adjective", "practical"),
    "preamble": ("noun", "introduction"),
    "precarious": ("adjective", "unsafe; shaky"),
    "precede": ("verb", "come before"),
    "precedent": ("noun", "earlier example"),
    "precept": ("noun", "rule of conduct"),
    "precipitate": ("verb", "cause suddenly"),
    "preclude": ("verb", "prevent"),
    "precocious": ("adjective", "smart too early"),
    "predator": ("noun", "hunter"),
    "predecessor": ("noun", "earlier holder"),
    "predicament": ("noun", "difficult situation"),
    "predilection": ("noun", "strong liking"),
    "predominant": ("adjective", "strongest; main"),
    "preeminent": ("adjective", "above all others"),
    "preempt": ("verb", "act first to block"),
    "preface": ("noun", "book introduction"),
    "premise": ("noun", "starting idea"),
    "premium": ("noun", "extra value or price"),
    "preponderance": ("noun", "greater weight"),
    "preposterous": ("adjective", "absurd"),
    "prerogative": ("noun", "special right"),
    "presage": ("verb", "foretell"),
    "prescribe": ("verb", "order; advise"),
    "prescient": ("adjective", "knowing the future"),
    "preside": ("verb", "lead a meeting"),
    "press": ("verb", "urge strongly"),
    "prestige": ("noun", "high respect"),
    "presumably": ("adverb", "probably"),
    "presume": ("verb", "assume"),
    "pretentious": ("adjective", "showing off"),
    "prevail": ("verb", "win; be common"),
    "prevalent": ("adjective", "widespread"),
    "prevaricate": ("verb", "avoid telling truth"),
    "prey": ("noun", "hunted victim"),
    "primarily": ("adverb", "mainly"),
    "prime": ("adjective", "main; best"),
    "primitive": ("adjective", "simple and early"),
    "principal": ("adjective", "main"),
    "principle": ("noun", "basic rule"),
    "pristine": ("adjective", "pure; untouched"),
    "probe": ("verb", "investigate deeply"),
    "procrastinate": ("verb", "delay doing things"),
    "prodigal": ("adjective", "wasteful"),
    "prodigious": ("adjective", "huge; amazing"),
    "prolific": ("adjective", "producing much"),
    "prolong": ("verb", "make longer"),
    "prominent": ("adjective", "standing out"),
    "prompt": ("adjective", "quick; on time"),
    "prone": ("adjective", "likely to"),
    "propagate": ("verb", "spread; breed"),
    "propel": ("verb", "push forward"),
    "propensity": ("noun", "natural tendency"),
    "propitious": ("adjective", "favorable"),
    "proponent": ("noun", "supporter"),
    "propriety": ("noun", "proper behavior"),
    "prosaic": ("adjective", "dull; ordinary"),
    "prose": ("noun", "ordinary writing"),
    "prospect": ("noun", "future chance"),
    "prosper": ("verb", "succeed; thrive"),
    "protagonist": ("noun", "main character"),
    "protocol": ("noun", "official rules"),
    "prototype": ("noun", "first model"),
    "provincial": ("adjective", "narrow; rural"),
    "provision": ("noun", "supply; condition"),
    "provoke": ("verb", "anger; stir up"),
    "prowess": ("noun", "great skill"),
    "proxy": ("noun", "stand-in"),
    "prudent": ("adjective", "wise and careful"),
    "pseudonym": ("noun", "false name"),
    "pugnacious": ("adjective", "eager to fight"),
    "pundit": ("noun", "expert commentator"),
    "pungent": ("adjective", "sharp-smelling"),
    "punitive": ("adjective", "punishing"),
    "purport": ("verb", "claim to be"),
    "quagmire": ("noun", "muddy mess; trap"),
    "quaint": ("adjective", "charmingly old"),
    "quandary": ("noun", "hard choice"),
    "quest": ("noun", "search"),
    "quintessential": ("adjective", "perfect example of"),
    "quirk": ("noun", "odd habit"),
    "quixotic": ("adjective", "romantically unrealistic"),
    "quota": ("noun", "fixed share"),
    "radical": ("adjective", "extreme; basic"),
    "rail": ("verb", "complain bitterly"),
    "rampant": ("adjective", "spreading wildly"),
    "rancor": ("noun", "deep hatred"),
    "rapacious": ("adjective", "greedy"),
    "rapport": ("noun", "friendly understanding"),
    "ratify": ("verb", "approve officially"),
    "rational": ("adjective", "logical"),
    "raucous": ("adjective", "harshly loud"),
    "ravage": ("verb", "destroy"),
    "ravenous": ("adjective", "very hungry"),
    "realm": ("noun", "kingdom; area"),
    "reap": ("verb", "harvest; gain"),
    "rebuff": ("verb", "reject bluntly"),
    "rebuke": ("verb", "scold"),
    "rebut": ("verb", "prove wrong"),
    "recalcitrant": ("adjective", "stubbornly disobedient"),
    "recant": ("verb", "take back words"),
    "recapitulate": ("verb", "sum up"),
    "recede": ("verb", "move back"),
    "reciprocate": ("verb", "return in kind"),
    "reclaim": ("verb", "take back"),
    "recluse": ("noun", "loner"),
    "recoil": ("verb", "jump back"),
    "recompense": ("noun", "payment for loss"),
    "reconcile": ("verb", "make friendly again"),
    "recondite": ("adjective", "hard to understand"),
    "recourse": ("noun", "help turned to"),
    "rectitude": ("noun", "honesty"),
    "recur": ("verb", "happen again"),
    "redeem": ("verb", "buy back; save"),
    "redolent": ("adjective", "smelling of; reminding of"),
    "redress": ("verb", "fix a wrong"),
    "redundant": ("adjective", "extra; wordy"),
    "refine": ("verb", "improve; purify"),
    "refrain": ("verb", "hold back from"),
    "refuge": ("noun", "shelter"),
    "refute": ("verb", "prove wrong"),
    "regime": ("noun", "ruling system"),
    "reign": ("verb", "rule as king"),
    "reiterate": ("verb", "repeat"),
    "rejoinder": ("noun", "sharp reply"),
    "relegate": ("verb", "send down; assign"),
    "relent": ("verb", "soften; give in"),
    "relentless": ("adjective", "never stopping"),
    "relic": ("noun", "old surviving thing"),
    "relinquish": ("verb", "give up"),
    "relish": ("verb", "enjoy greatly"),
    "reluctant": ("adjective", "unwilling"),
    "remedy": ("noun", "cure; fix"),
    "remnant": ("noun", "leftover piece"),
    "remorse": ("noun", "deep regret"),
    "render": ("verb", "give; depict"),
    "renegade": ("noun", "deserter"),
    "renege": ("verb", "break a promise"),
    "renounce": ("verb", "give up formally"),
    "renown": ("noun", "fame"),
    "repeal": ("verb", "cancel a law"),
    "repel": ("verb", "drive back"),
    "repent": ("verb", "feel sorry for sin"),
    "repercussion": ("noun", "after-effect"),
    "replenish": ("verb", "fill up again"),
    "replete": ("adjective", "full of"),
    "repress": ("verb", "hold down"),
    "reprieve": ("noun", "delay of punishment"),
    "reprimand": ("verb", "scold officially"),
    "reproach": ("verb", "blame"),
    "repudiate": ("verb", "reject"),
    "repugnant": ("adjective", "disgusting"),
    "requisite": ("adjective", "needed"),
    "rescind": ("verb", "cancel"),
    "resent": ("verb", "feel bitter about"),
    "reside": ("verb", "live in"),
    "residual": ("adjective", "left over"),
    "resign": ("verb", "quit a job"),
    "resilient": ("adjective", "bouncing back fast"),
    "resolute": ("adjective", "firmly decided"),
    "resonant": ("adjective", "echoing; deep"),
    "respite": ("noun", "short rest"),
    "resplendent": ("adjective", "shining brightly"),
    "restive": ("adjective", "restless"),
    "restrain": ("verb", "hold back"),
    "resurgent": ("adjective", "rising again"),
    "retain": ("verb", "keep"),
    "retaliate": ("verb", "strike back"),
    "reticent": ("adjective", "quiet; reserved"),
    "retort": ("verb", "reply sharply"),
    "retract": ("verb", "take back"),
    "retribution": ("noun", "punishment"),
    "retrieve": ("verb", "get back"),
    "revere": ("verb", "deeply respect"),
    "revert": ("verb", "go back to"),
    "revoke": ("verb", "cancel"),
    "rhetoric": ("noun", "art of speaking well"),
    "rhetorical": ("adjective", "for effect, not answer"),
    "ridicule": ("verb", "mock"),
    "rife": ("adjective", "widespread"),
    "rift": ("noun", "split; crack"),
    "righteous": ("adjective", "morally right"),
    "rigor": ("noun", "strictness; hardship"),
    "rigorous": ("adjective", "very strict; thorough"),
    "rite": ("noun", "ceremony"),
    "riveting": ("adjective", "fascinating"),
    "robust": ("adjective", "strong and healthy"),
    "rogue": ("noun", "dishonest person"),
    "rote": ("noun", "memory without thought"),
    "rubric": ("noun", "scoring guide"),
    "rudimentary": ("adjective", "basic; simple"),
    "rue": ("verb", "regret"),
    "ruminate": ("verb", "think deeply"),
    "ruse": ("noun", "trick"),
    "ruthless": ("adjective", "without mercy"),
    "sagacious": ("adjective", "very wise"),
    "sage": ("noun", "wise person"),
    "salient": ("adjective", "standing out"),
    "salutary": ("adjective", "good for you"),
    "salvage": ("verb", "save from wreck"),
    "sanctimonious": ("adjective", "falsely holy"),
    "sanction": ("verb", "approve; punish"),
    "sanctuary": ("noun", "safe shelter"),
    "sanguine": ("adjective", "cheerfully hopeful"),
    "sap": ("verb", "drain strength of"),
    "sardonic": ("adjective", "mocking"),
    "satire": ("noun", "mocking humor"),
    "saturate": ("verb", "soak fully"),
    "savor": ("verb", "enjoy fully"),
    "scant": ("adjective", "barely enough"),
    "scapegoat": ("noun", "blamed innocent"),
    "scarce": ("adjective", "rare; hard to find"),
    "scathing": ("adjective", "bitterly harsh"),
    "scoff": ("verb", "mock"),
    "scope": ("noun", "range"),
    "scorn": ("verb", "despise"),
    "scour": ("verb", "search thoroughly"),
    "scourge": ("noun", "cause of pain"),
    "scrupulous": ("adjective", "very honest; thorough"),
    "scrutinize": ("verb", "examine closely"),
    "seclude": ("verb", "shut away"),
    "sedate": ("adjective", "calm"),
    "sedentary": ("adjective", "sitting much"),
    "segregate": ("verb", "separate by group"),
    "seminal": ("adjective", "groundbreaking"),
    "serene": ("adjective", "calm and clear"),
    "serendipity": ("noun", "lucky discovery"),
    "servile": ("adjective", "too obedient"),
    "sever": ("verb", "cut off"),
    "shoddy": ("adjective", "poorly made"),
    "shrewd": ("adjective", "clever in business"),
    "shun": ("verb", "avoid"),
    "siege": ("noun", "surrounding attack"),
    "sift": ("verb", "sort through"),
    "signify": ("verb", "mean"),
    "simile": ("noun", "like/as comparison"),
    "simultaneous": ("adjective", "at the same time"),
    "sinister": ("adjective", "evil-looking"),
    "skeptic": ("noun", "doubter"),
    "sluggish": ("adjective", "slow"),
    "sober": ("adjective", "serious; not drunk"),
    "solicit": ("verb", "ask for"),
    "solitary": ("adjective", "alone"),
    "solvent": ("adjective", "able to pay debts"),
    "somber": ("adjective", "dark and gloomy"),
    "soothe": ("verb", "calm"),
    "sophisticated": ("adjective", "complex; worldly"),
    "sordid": ("adjective", "dirty; shameful"),
    "sovereign": ("noun", "ruler; king"),
    "sparse": ("adjective", "thinly spread"),
    "spartan": ("adjective", "very plain"),
    "specious": ("adjective", "looking right but wrong"),
    "spectrum": ("noun", "full range"),
    "speculate": ("verb", "guess"),
    "spendthrift": ("noun", "wasteful spender"),
    "sporadic": ("adjective", "occasional"),
    "spurious": ("adjective", "false"),
    "squalid": ("adjective", "filthy"),
    "squander": ("verb", "waste"),
    "stagnant": ("adjective", "not flowing; stale"),
    "staid": ("adjective", "serious and dull"),
    "stalwart": ("adjective", "strong and loyal"),
    "stanza": ("noun", "verse paragraph"),
    "static": ("adjective", "not moving"),
    "statute": ("noun", "written law"),
    "steadfast": ("adjective", "firmly loyal"),
    "stigma": ("noun", "mark of shame"),
    "stilted": ("adjective", "stiff and formal"),
    "stimulate": ("verb", "excite; encourage"),
    "stingy": ("adjective", "not generous"),
    "stint": ("noun", "fixed period of work"),
    "stoic": ("adjective", "bearing pain calmly"),
    "stolid": ("adjective", "showing little feeling"),
    "stratagem": ("noun", "clever trick"),
    "stratum": ("noun", "a layer"),
    "strident": ("adjective", "harshly loud"),
    "strife": ("noun", "conflict"),
    "stringent": ("adjective", "very strict"),
    "strut": ("verb", "walk proudly"),
    "stultify": ("verb", "make stupid"),
    "stupefy": ("verb", "amaze; stun"),
    "sturdy": ("adjective", "strong"),
    "subdue": ("verb", "overcome; calm"),
    "subjective": ("adjective", "personal; biased"),
    "subjugate": ("verb", "conquer"),
    "sublime": ("adjective", "grand; noble"),
    "submerge": ("verb", "sink under"),
    "submit": ("verb", "give in; hand in"),
    "subordinate": ("adjective", "lower in rank"),
    "subsequent": ("adjective", "following"),
    "subservient": ("adjective", "too obedient"),
    "subside": ("verb", "sink down; lessen"),
    "subsidiary": ("adjective", "secondary"),
    "subsidize": ("verb", "fund with money"),
    "subsist": ("verb", "barely survive"),
    "substance": ("noun", "matter; meaning"),
    "substantial": ("adjective", "large; solid"),
    "substantiate": ("verb", "prove with facts"),
    "subterfuge": ("noun", "trick to escape"),
    "subtle": ("adjective", "slight; clever"),
    "subversive": ("adjective", "trying to overthrow"),
    "succinct": ("adjective", "brief and clear"),
    "succumb": ("verb", "give in; die"),
    "suffice": ("verb", "be enough"),
    "suffrage": ("noun", "right to vote"),
    "sullen": ("adjective", "gloomily silent"),
    "sully": ("verb", "dirty; stain"),
    "sumptuous": ("adjective", "luxurious"),
    "sunder": ("verb", "split apart"),
    "sundry": ("adjective", "various"),
    "supercilious": ("adjective", "proudly superior"),
    "superficial": ("adjective", "on the surface only"),
    "superfluous": ("adjective", "extra; unneeded"),
    "supplant": ("verb", "replace"),
    "supple": ("adjective", "flexible"),
    "supplicate": ("verb", "beg humbly"),
    "suppress": ("verb", "hold down"),
    "surfeit": ("noun", "too much"),
    "surly": ("adjective", "rude and gloomy"),
    "surmise": ("verb", "guess"),
    "surmount": ("verb", "overcome"),
    "surpass": ("verb", "go beyond"),
    "surplus": ("noun", "extra amount"),
    "surreptitious": ("adjective", "secretive"),
    "surrogate": ("noun", "substitute"),
    "surveillance": ("noun", "close watch"),
    "susceptible": ("adjective", "easily affected"),
    "suspend": ("verb", "hang; stop for a time"),
    "sustain": ("verb", "keep going"),
    "svelte": ("adjective", "slim and graceful"),
    "swagger": ("verb", "walk proudly"),
    "swarthy": ("adjective", "dark-skinned"),
    "swindle": ("verb", "cheat out of money"),
    "sycophant": ("noun", "flatterer"),
    "symbiosis": ("noun", "living together helpfully"),
    "symmetry": ("noun", "balanced shape"),
    "symposium": ("noun", "meeting to discuss"),
    "synchronous": ("adjective", "at the same time"),
    "synergy": ("noun", "combined power"),
    "synopsis": ("noun", "short summary"),
    "synthesis": ("noun", "combining into whole"),
    "tacit": ("adjective", "silent; understood"),
    "taciturn": ("adjective", "quiet"),
    "tackle": ("verb", "deal with"),
    "tactful": ("adjective", "careful not to offend"),
    "talisman": ("noun", "lucky charm"),
    "tangible": ("adjective", "can be touched; real"),
    "tantalize": ("verb", "tease with hope"),
    "tantamount": ("adjective", "equal to"),
    "tantrum": ("noun", "fit of anger"),
    "tardy": ("adjective", "late"),
    "tawdry": ("adjective", "cheap and flashy"),
    "tedious": ("adjective", "boring and long"),
    "temerity": ("noun", "boldness"),
    "temper": ("verb", "soften; control"),
    "temperament": ("noun", "nature; mood"),
    "temperate": ("adjective", "mild"),
    "tempest": ("noun", "violent storm"),
    "temporal": ("adjective", "about time"),
    "tenable": ("adjective", "can be defended"),
    "tenacious": ("adjective", "holding on firmly"),
    "tendentious": ("adjective", "biased"),
    "tenet": ("noun", "belief; principle"),
    "tensile": ("adjective", "stretchable"),
    "tentative": ("adjective", "uncertain; trial"),
    "tenuous": ("adjective", "thin; weak"),
    "tenure": ("noun", "holding of office"),
    "tepid": ("adjective", "lukewarm"),
    "verbatim": ("adverb", "word for word"),
    "verbose": ("adjective", "wordy"),
    "verdant": ("adjective", "green with plants"),
    "verdict": ("noun", "decision"),
    "verge": ("noun", "edge"),
    "verify": ("verb", "prove true"),
    "verisimilitude": ("noun", "appearance of truth"),
    "veritable": ("adjective", "true; real"),
    "vernacular": ("noun", "everyday language"),
    "versatile": ("adjective", "able to do many things"),
    "vertex": ("noun", "top point; corner"),
    "vertigo": ("noun", "dizziness"),
    "verve": ("noun", "energy; spirit"),
    "vestige": ("noun", "small trace left"),
    "vex": ("verb", "annoy"),
    "viable": ("adjective", "able to work"),
    "vicarious": ("adjective", "felt through others"),
    "vicissitude": ("noun", "change of fortune"),
    "victimize": ("verb", "make a victim of"),
    "vigilant": ("adjective", "watchful"),
    "vigor": ("noun", "energy"),
    "vilify": ("verb", "speak evil of"),
    "vindicate": ("verb", "clear from blame"),
    "vindictive": ("adjective", "revengeful"),
    "virtuoso": ("noun", "master performer"),
    "virulent": ("adjective", "poisonous; hateful"),
    "viscous": ("adjective", "thick and sticky"),
    "visionary": ("adjective", "dreaming of future"),
    "vital": ("adjective", "essential for life"),
    "vitiate": ("verb", "spoil; corrupt"),
    "vitriolic": ("adjective", "bitterly harsh"),
    "vituperate": ("verb", "blame abusively"),
    "vivacious": ("adjective", "lively"),
    "vivid": ("adjective", "bright; clear"),
    "vocation": ("noun", "calling; job"),
    "vociferous": ("adjective", "loudly demanding"),
    "vogue": ("noun", "fashion"),
    "volatile": ("adjective", "changing fast"),
    "volition": ("noun", "free will"),
    "voluble": ("adjective", "talkative"),
    "voluminous": ("adjective", "very large"),
    "voracious": ("adjective", "greedy for food or knowledge"),
    "vortex": ("noun", "whirlpool"),
    "votary": ("noun", "devoted follower"),
    "vouch": ("verb", "guarantee"),
    "vulgar": ("adjective", "crude; common"),
    "vulnerable": ("adjective", "easily hurt"),
    "wane": ("verb", "grow smaller"),
    "wanton": ("adjective", "wild; without reason"),
    "wary": ("adjective", "careful"),
    "waver": ("verb", "shake; hesitate"),
    "wax": ("verb", "grow larger"),
    "whimsical": ("adjective", "playfully odd"),
    "wily": ("adjective", "sly"),
    "wince": ("verb", "shrink from pain"),
    "winsome": ("adjective", "charming"),
    "wistful": ("adjective", "sadly longing"),
    "withdrawn": ("adjective", "shy; removed"),
    "wither": ("verb", "dry up; fade"),
    "withhold": ("verb", "hold back"),
    "withstand": ("verb", "resist"),
    "witty": ("adjective", "cleverly funny"),
    "woe": ("noun", "great sadness"),
    "wrest": ("verb", "pull away forcefully"),
    "wretched": ("adjective", "miserable"),
    "wry": ("adjective", "twisted; dryly funny"),
    "xenophobia": ("noun", "fear of foreigners"),
    "yoke": ("verb", "join together"),
    "zeal": ("noun", "great energy for a cause"),
    "zealot": ("noun", "fanatic"),
    "zenith": ("noun", "highest point"),
    "zephyr": ("noun", "gentle breeze"),
    # Math word-problem helpers
    "consecutive": ("adjective", "following in order"),
    "integer": ("noun", "whole number"),
    "quotient": ("noun", "result of division"),
    "remainder": ("noun", "amount left over"),
    "coefficient": ("noun", "number before a letter"),
    "proportional": ("adjective", "matching in size or amount"),
    "median": ("noun", "middle value"),
    "mode": ("noun", "most common value"),
    "outlier": ("noun", "data point far from others"),
    "distribution": ("noun", "spread of data"),
    "deviate": ("verb", "move away from normal"),
    "estimate": ("verb", "guess the amount of"),
    "approximate": ("adjective", "nearly exact"),
}
